---platform: linuximage_resource:   type: docker-image  source:    repository: maven    tag: latest    inputs:  - name: ownmavenhelloworld  outputs:  - name: resource-app  run:  path: ownmavenhelloworld/ci/build.sh
